version: "3.9"

services:
  creditsvc:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.creditsvc
    volumes:
      - ledgerdata:/srv/data
    ports:
      - "7000:7000"

volumes:
  ledgerdata: {}
