services:
  ledgersvc:
    image: ghcr.io/tyemirov/ledger:latest
    env_file:
      - .env.ledgersvc
    volumes:
      - ledgerdata:/srv/data
    ports:
      - "50051:50051"

volumes:
  ledgerdata: {}
