services:
  ledgersvc:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.ledgersvc
    volumes:
      - ledgerdata:/srv/data
    ports:
      - "50051:50051"

volumes:
  ledgerdata: {}
