services:
  ledgerd:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.ledger
    volumes:
      - ledger-data:/srv/data
    ports:
      - "50051:50051"

volumes:
  ledger-data: {}
