services:
  creditsvc:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.creditsvc
    volumes:
      - ledgerdata:/srv/data
    ports:
      - "50051:50051"

volumes:
  ledgerdata: {}
